### ISSUE TITLE
Keep Training and app crash

### ISSUE THREAD

**Issue by skynetandroiddev** [Lauszus/FaceRecognitionApp#25]
Hello,

I have added 3 face.
Now when i try to recognize the face it says **Keep training..**
Then i'll click on the name of scanned face then app will crash with following error messages.

When i'll try the same with two face, it'll work fine.
Please give me a solution to fix this.

```
FaceRecognitionApp-1.2.2/app/src/main/cpp/../../../../Eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<Eigen::Matrix<float, -1, -1, 0, -1, -1>, -1, 1, true>::Block(XprType &, Eigen::Index) [XprType = Eigen::Matrix<float, -1, -1, 0, -1, -1>, BlockRows = -1, BlockCols = 1, InnerPanel = true]: assertion "(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))" failed
com.lauszus.facerecognitionapp A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 22110 (AsyncTask #4), pid 21865 (erecognitionapp)
```

**Comment by Lauszus** [comment]
@skynetandroiddev thanks a lot for the report. I finally took some time to look into it and I found a phone were I could replicate the issue. The issue was when the aspect ratio of the front and back camera was not the same would cause the app to crash.

The following commit should fix it: a94591ab9781ca2ec70b25d46a5f9adde290ae40.

I'll release a new version of the app shortly. Again thanks for reporting the issue.
