### ISSUE TITLE
Unable to remove fisherfaces and getting 1 warning when trying to run on my mobile

### ISSUE THREAD

**Issue by Pittu7** [Lauszus/FaceRecognitionApp#41]
Hi
Can you please help me with me the below issues:
1, unable to remove fisherfaces in the app. I have gone through your comment but unable to understand where to hardcode "useEigenfaces = True"
2, Getting 1 warning when trying to run the app on my mobile device connected via USB as:
ABIs [armeabi-v7a,armeabi] set by 'android.injected.build.abi' gradle flag contained 'ARMEABI' not targeted by this project.
Because of the above warning, have tried to send APK file via bluetooth but the app has crashed and closing with the message "Face Recognition has stopped"
Please respond as soon as possible.
Thanks

**Comment by Lauszus** [comment]
1. Simply just comment out this code:
https://github.com/Lauszus/FaceRecognitionApp/blob/0cdb1dbb8159fe43170b2ca66ae62c63634785a7/app/src/main/java/com/lauszus/facerecognitionapp/FaceRecognitionAppActivity.java#L300-L323

Then replace: https://github.com/Lauszus/FaceRecognitionApp/blob/0cdb1dbb8159fe43170b2ca66ae62c63634785a7/app/src/main/java/com/lauszus/facerecognitionapp/FaceRecognitionAppActivity.java#L327 
with: 

```java
useEigenfaces = true
```

2. Are you using the latest release? This should have been fixed in https://github.com/Lauszus/FaceRecognitionApp/commit/a63b3442488b6dad9f2d5a35b1cd3764a54920e6 and https://github.com/Lauszus/FaceRecognitionApp/commit/79020d2f40a6cec95c1567a30f11042d13fe849c

**Comment by Lauszus** [comment]
I'm closing this due to a lack of response. Feel free to reopen if you still are having issues.
